-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKRtnOhDDa8mZ3oh2
NfY8QuO9CdygBAQMJa9x+UhRDOygCgYIKoZIzj0DAQehRANCAARvvXD4E0uK0+XL
5Ry0/h0bOB3zRtM/gl4s2Z3hCtZFUiOPwJ3HYG54OHHTrsfAlaNNHwvycmQozBr8
elQgcKRS
-----END PRIVATE KEY-----